### ISSUE TITLE
about

### ISSUE THREAD

**Issue by bwangelme** [anotherbwangel/blog-comment#6]
https://bwangelme.github.io/about/

**Comment by bwangelme** [comment]
迁移到了 Utterances

**Comment by bwangelme** [comment]
为主题 [hugo-theme-even](https://github.com/olOwOlo/hugo-theme-even) 添加了 Utterances 评论的功能

**Comment by zhscn** [comment]
@bwangelme 我clone你的分支并且也在`config.toml`中设置了,`comment`仓库也安装了utterances app,为什么我的页面还是没有评论呢
这是我的设置
```
  [params.utteranc]
    enable = true
    repo = "zhscn/comment"
    issueTerm = "pathname"
    theme = "github-light"
```

**Comment by bwangelme** [comment]
请问 theme clone 的是这个仓库么 https://github.com/bwangelme/hugo-theme-even

配置应该是这样的
```tomp
  [params.utterances]       # https://utteranc.es/
    owner = "anotherbwangel"              # Your GitHub ID
    repo = "blog-comment"               # The repo to store comments
```

@zhscn 可以把你的代码贴上来看一下么。

**Comment by zhscn** [comment]
已经解决了.是`  [params.utterances]`的原因,我以前使用的是`[params.utteranc]`,更改之后可以正常评论了

**Comment by bwangelme** [comment]
https://github.com/bwangelme/hugo-theme-even/commit/125e7e97144c4e26b7e14e2c88ce3dfc4a40db39#diff-4bc063bcdcf2e635a36bd0d8d6273ad8R100

嗯，我读取的配置名称是 utterances

**Comment by bwangelme** [comment]
目前使用的 utterances 评论系统，它是根据文章路径去查找 issues 的。

我在hugo 的配置文件中设置的文件的路径是 `/year/month/day/filename`。所以只要文章的文件名不变，评论是不会匹配不上的。

同时由于路径名不再使用文章的名称，所以在 issues 中再也看不到 `2018/08/14/%E7%B4%A0%E6%95%B0%E7%94%9F%E6%88%90%E5%99%A8/` 这种名字了

**Comment by slarsar** [comment]
博主您好呀，我也是使用和你一样的even主题， 但是我clone了even的仓库到我的themes目录下之后，拷贝examplesite下的config.toml和content/* 到我的主目录后，执行hugo server却没能在首页看到每篇post的预览，你觉得可能是哪里出了问题呢？

**Comment by bwangelme** [comment]
@slarsar 可以贴一下你的仓库地址吗？

**Comment by slarsar** [comment]
> @slarsar 可以贴一下你的仓库地址吗？

我已经不用这个主题了，w3css了哈。

**Comment by liupeidong0620** [comment]
博主你好，评论系统不起作用？
https://liupeidong0620.github.io/post/test/chinese-preview/

然后'关于'可以看到评论
https://liupeidong0620.github.io/about/

配置文件
https://github.com/liupeidong0620/liupeidong0620.github.io/blob/source/config.toml

请教下

**Comment by xiaohao890809** [comment]
请问网页底部出现了大量空白这个问题是怎么解决的呢？

**Comment by bwangelme** [comment]
https://github.com/olOwOlo/hugo-theme-even/pull/225/files

照着这个commit改动了那一行后，重新build(`npm build`)一下就可以了。

**Comment by bwangelme** [comment]
> 请问网页底部出现了大量空白这个问题是怎么解决的呢？

@xiaohao890809 

https://github.com/olOwOlo/hugo-theme-even/pull/225/files

照着这个commit改动了那一行后，重新build(npm build)一下就可以了。

**Comment by ou-bing** [comment]
hello, hugo-theme-even 使用 utterances 评论系统 只需要配置  params.utterances 么？
为啥我配了之后没效果...
这是我的配置：
  [params.utterances]
    owner = "ou-bing"
    repo = "myblog"

**Comment by bwangelme** [comment]
@ou-bing 

1. 确认 [utterances App](https://github.com/apps/utterances) 已经安装到了你的仓库(ou-bing/myblog)中。
2. 打开你的博客，在 Chrome 控制台确认 
  + https://utteranc.es/client.js
  + https://utteranc.es/utterances.html
  + https://utteranc.es/utterances.8ca43796.js
  + https://utteranc.es/stylesheets/themes/github-light/utterances.css 

是否被正确请求到了。
